#!/usr/bin/env bash
# This Bash (init) script manages manage_my_process.

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"
SCRIPT_NAME=$(basename "$0")

start() 
{
	if [ -e "$PID_FILE" ];
	then
		echo "$PROCESS_NAME is already running."
		exit 1
	fi
	
	./manage_my_processs
	echo $! > "$PID_FILE"
	echo "$PROCESS_NAME started"
}

stop() 
{
	if [ -e "$PID_FILE" ];
	then
		kill -9 "$(cat "$PID_FILE")"
		rm "$PID_FILE"
		echo "$PROCESS_NAME stopped"
	else
		echo "$PROCESS_NAME is not running."
		exit 1
	fi
}

restart()
{
	   echo "$PROCESS_NAME restarted"
}

usage() 
{
	echo "Usage: $SCRIPT_NAME {start|stop|restart}"
	exit 1
}

if [ "$#" -eq 1 ]; then
	case "$1" in
		start)
			start
			;;
		stop)
			stop
			;;
		restart)
			restart
			;;
		*)
			usage
			;;
	esac
else
	usage
fi
