#!/usr/bin/env bash
# This Bash (init) script manages manage_my_process.

PID_FILE="/var/run/my_process.pid"
PROCESS_NAME="manage_my_process"

start() 
{
	if [ -e "$PID_FILE" ];
	then
		echo "$PROCESS_NAME is already running."
		exit 1
	fi
	
	 ./"$PROCESS_NAME" &
	echo $! > "$PID_FILE"
	echo "$PROCESS_NAME started"
}

stop() 
{
	if [ -f "$PID_FILE" ];
	then
		kill -TERM "$(cat "$PID_FILE")"
		rm $PID_FILE
		echo "$PROCESS_NAME stopped"
	else
		echo "$PROCESS_NAME is not running."
		exit 1
	fi
}

restart()
{
	if [ -f "$PID_FILE" ];
        then
		echo "$PROCESS_NAME restarted"
		else
        echo "$PROCESS_NAME is not running."
        exit 1
    fi
}

usage() 
{
	echo "Usage: $PROCESS_NAME {start|stop|restart}"
	exit 1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		usage
		;;
esac
