#!/usr/bin/env bash
# This script Indefinitely writes I am alive! to the file /tmp/my_process and In between every I am alive! message, it pause for 2 seconds

while start; do
echo "I am alive!" >> /tmp/my_process
sleep 2
done
